default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: db

development:
  <<: *default
  database: sample_rails6_app_development

test:
  <<: *default
  database: sample_rails6_app_test

production:
  <<: *default
  database: sample_rails6_app_production
  username: sample_rails6_app
  password: <%= ENV['SAMPLE_RAILS6_APP_DATABASE_PASSWORD'] %>
